# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4c089448b5084d5424630d1f1ca349addbebb54b7c7b0740d1baebe1012bc863f1a561f0108f1bd699d8311e4bf7da83074aa42a8f8366147ac0810b831aeb07

test:
  secret_key_base: 183f244c9f140d351cf0893b1877d5bd831ea834934ba6e50a444c8c5e70dc6b566b205077cc87f0ecc9f3bb7bbdc749d3f97d96a8ca5a8d4a8c75ba176dde27

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
